# Generated by Django 3.1.4 on 2021-07-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30)),
                ('armazenamento', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_revenda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('create_at', models.DateField()),
            ],
        ),
    ]
