# Generated by Django 3.1.4 on 2021-07-28 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20210727_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='criado_em',
            field=models.DateField(auto_created=django.utils.timezone.now),
        ),
    ]
