# Generated by Django 3.1.4 on 2021-08-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20210728_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='armazenamento',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(default='ssd', max_length=30, verbose_name='Tipo de Produto'),
        ),
    ]
