# Generated by Django 3.1.4 on 2021-08-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='create_at',
            new_name='criado_em',
        ),
    ]
