# Generated by Django 3.1.4 on 2021-08-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_auto_20210805_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='criado_em',
            field=models.DateField(auto_now_add=True),
        ),
    ]
