# Generated by Django 3.1.4 on 2021-08-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20210728_0005'),
        ('venda', '0005_venda_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produtos_fk',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='venda',
            name='bairro',
            field=models.CharField(default='00', max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='cep',
            field=models.CharField(default='00', max_length=30, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='cidade',
            field=models.CharField(choices=[('juazeiro_do_norte', 'Juazeiro do Norte'), ('crato', 'Crato')], default='00', max_length=50, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='contato',
            field=models.CharField(default='00', max_length=50, verbose_name='Contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='numero',
            field=models.PositiveIntegerField(default='00', verbose_name='Nº'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='rua',
            field=models.CharField(default='00', max_length=100, verbose_name='Rua'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('desconto', models.PositiveIntegerField(verbose_name='Desconto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venda.venda')),
            ],
        ),
    ]
