# Generated by Django 3.1.4 on 2021-08-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20210728_0005'),
        ('venda', '0006_auto_20210820_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='produtos_fk',
            field=models.ManyToManyField(through='venda.VendaProduto', to='produto.Produto', verbose_name='Produtos'),
        ),
    ]
