# Generated by Django 3.1.4 on 2021-08-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0007_venda_produtos_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_de_contato',
            field=models.CharField(default='Whatsapp', max_length=200, verbose_name='Tipo de Contato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='comprador',
            field=models.CharField(max_length=50, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='contato',
            field=models.CharField(max_length=50, verbose_name='Telefone'),
        ),
    ]
