# Generated by Django 3.1.4 on 2021-08-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0008_auto_20210820_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
