# Generated by Django 3.1.4 on 2021-08-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0010_auto_20210820_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
    ]
