# Generated by Django 3.1.4 on 2021-08-22 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venda', '0012_venda_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaproduto',
            name='venda',
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('selecao_produtos', 'Aguardando Seleção de Produtos'), ('a_caminho', 'A caminho'), ('entregue', 'Entregue')], default='selecao_produtos', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipo_de_contato',
            field=models.CharField(choices=[('redes_sociais', 'Redes Sociais'), ('indicacao', 'Indicação'), ('wpp', 'WhatsApp')], max_length=200, verbose_name='Tipo de Contato'),
        ),
    ]
