# Generated by Django 3.1.4 on 2021-08-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0017_auto_20210822_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('a_caminho', 'A caminho'), ('entregue', 'Entregue')], default='em_andamento', max_length=50, verbose_name='Status'),
        ),
    ]
